name: Create Production Builds

on:
  push:
    branches: ['master']

jobs:
    build_android:
      type: build #creates a production build for android
      params:
        platform: android
    build_ios:
      type: build #creates a production build for ios
      params:
        platform: ios

