on:
  push:
    branches: ['master']

jobs:
  build_android:
    name: Build Android app
    type: build
    params:
      platform: android
      profile: production

  submit_android:
    name: Submit to Google Play Store
    needs: [build_android]
    type: submit
    params:
      platform: android
      build_id: 5a4f0f95-ff3b-43d7-a9da-48f144df0db8
